### ISSUE TITLE
ImportError: cannot import name GopherError

### ISSUE THREAD

**Issue by Tridas** [chinoogawa/instaBrute#12]
When I try using it I get this error:

Traceback (most recent call last):
  File "instaBrute.py", line 2, in <module>
    from mainLib import *
  File "C:\Users\kevindinh\Desktop\insta\mainLib.py", line 1, in <module>
    import mechanize
  File "C:\Python27\lib\site-packages\mechanize\__init__.py", line 85, in <module>
    from _mechanize import __version__
  File "C:\Python27\lib\site-packages\mechanize\_mechanize.py", line 14, in <module>
    from _useragent import UserAgentBase
  File "C:\Python27\lib\site-packages\mechanize\_useragent.py", line 17, in <module>
    import _urllib2
  File "C:\Python27\lib\site-packages\mechanize\_urllib2.py", line 3, in <module>
    from urllib2 import \
ImportError: cannot import name GopherError

**Comment by Coto16** [comment]
Script has been patched by Instagram - Meaning it is no longer working.

**Comment by Tridas** [comment]
Oh ok, thanks

**Comment by aleperno** [comment]
Whether or not the "vuln" is patched by Instagram has nothing to do with the question.
@Tridas as far as I can tell you're missing a dependency. Try executing
`pip install mechanize`
you can also run
`pip freeze` 
and check which modules are currently installed.

**Comment by Coto16** [comment]
@aleperno Yes, you're correct, however I assumed that he just wanted to use the Application, solely for Instagram. I've used this program for other [brute-forcing] Automations, came pretty handy, but I doulbt that's what he wanted to do. :/
