### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by djscoobyg2** [chinoogawa/instaBrute#20]
When I start the command, all it does is crash firefox, then gives me this error code.

http://prntscr.com/c1kka2

**Comment by aleperno** [comment]
Please attach your selenium package version and Firefox Browser version.

**Comment by djscoobyg2** [comment]
I just installed selenium with cmd and firefox 48

**Comment by djscoobyg2** [comment]
@aleperno

**Comment by djscoobyg2** [comment]
any fix anyone?

**Comment by Chandler255** [comment]
Try reinstalling selenium.

**Comment by djscoobyg2** [comment]
I have done @Chandler255, it still didnt work, is there anything else i need to install

**Comment by djscoobyg2** [comment]
I have installed, optparse. mechanize, cookielib, simplejson, selenium

**Comment by aleperno** [comment]
@djscoobyg2 Please attach your Selenium version, there are known issues with given combinations of selenium version & firefox versions.
To check its version run: ```python -c "import selenium; print selenium.__version__"```

**Comment by djscoobyg2** [comment]
2.53.6

**Comment by aleperno** [comment]
I'll check and get back at you later @djscoobyg2

**Comment by djscoobyg2** [comment]
I'm going to move over to a VM on kali linux to stop all the hassle, thanks for your help anyway @aleperno , if you do find a solution, please let me know,

Thanks.

**Comment by Chandler255** [comment]
I went and updated Firefox and the driver never requested instagram.com, seems something is having a problem with it. I went ahead and rewrote it using the ChromeDriver and it works perfect through Chrome, see if that fixes it @djscoobyg2 . 
[instaBrute.zip](https://github.com/chinoogawa/instaBrute/files/404247/instaBrute.zip)

**Comment by djscoobyg2** [comment]
It didnt seem to work, do i have to install anything

**Comment by djscoobyg2** [comment]
`Traceback (most recent call last):
  File "instabrute.py", line 15, in <module>
    profile = webdriver.Chrome(chromedriver)
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application`

**Comment by Chandler255** [comment]
My bad, I use Mac which made me accidentally send the Mac chromedriver. I replaced it for you and made it an executable. @djscoobyg2 
[instaBrute.zip](https://github.com/chinoogawa/instaBrute/files/404415/instaBrute.zip)

**Comment by djscoobyg2** [comment]
http://prntscr.com/c22vxf @Chandler255

**Comment by karembino** [comment]
I am having an issue too , I am using windows 7 and python 2.7.3 , simplejson v.3.8.2 for win32 , selenium v.2.49.0  , mechanize v.0.2.5 ,and I used the instaBrute windows version and chrome driver and my chrome version is 52 and when I run the instaBrute.py   this error appears as in the screenshot
![untitled2](https://cloud.githubusercontent.com/assets/21139912/17830500/d4336ed6-66cd-11e6-9c14-1f51a31a3d2a.jpg)

**Comment by karembino** [comment]
And when I run instaBrute with the Mozilla driver it seems like @Chandler255 said the driver doesn't request instagram.com so what if I installed an older version of firefox would it work perfectly and if it does which version do you prefer or which version of Firefox worked perfectly with you . this is a screenshot when I used instaBrute running Firefox.
![untitled3](https://cloud.githubusercontent.com/assets/21139912/17830585/ec42e2c0-66cf-11e6-8190-de41138c7581.jpg)

**Comment by aleperno** [comment]
I'll pinn the script to specific lib versions to avoid newer versions to break the script.
This will be done as soon as possible.

**Comment by bd0r** [comment]
I have the same Error 
![untitled](https://cloud.githubusercontent.com/assets/23739528/21752650/5e504718-d5ed-11e6-9bd7-732a02bc0f9a.jpg)

**Comment by bd0r** [comment]
Solved , just install older Firefox version ...
