### ISSUE TITLE
STOPPED AT BLANK firefox page

### ISSUE THREAD

**Issue by nick7998** [chinoogawa/instaBrute#27]
I installed instabrute ,while running it after it shows "using 1 seconds of delay"
it did open a blank page on firefox ,then nothing 
few seconds latter it shows
Traceback (most recent call last):
File "C:\Users\User\Desktop\instaBrute-master\instaBrute.py", line 142, in <mo
dule>
main()
File "C:\Users\User\Desktop\instaBrute-master\instaBrute.py", line 132, in mai
n
driver = webdriver.Firefox(profile)
File "C:\Python27\lib\site-packages\selenium-2.53.1-py2.7.egg\selenium\webdriv
er\firefox\webdriver.py", line 103, in __init__
self.binary, timeout)
File "C:\Python27\lib\site-packages\selenium-2.53.1-py2.7.egg\selenium\webdriv
er\firefox\extension_connection.py", line 51, in __init__
self.binary.launch_browser(self.profile, timeout=timeout)
File "C:\Python27\lib\site-packages\selenium-2.53.1-py2.7.egg\selenium\webdriv
er\firefox\firefox_binary.py", line 68, in launch_browser
self._wait_until_connectable(timeout=timeout)
File "C:\Python27\lib\site-packages\selenium-2.53.1-py2.7.egg\selenium\webdriv
er\firefox\firefox_binary.py", line 106, in _wait_until_connectable
% (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile.
Profile Dir: c:\users\user\appdata\local\temp\tmp0p2qif If you specified a log_f
ile in the FirefoxBinary constructor, check it for details.

my firefox version is  48.0.2
using python 2.7 and selenium-2.53.1
can anyone tell me how to make it work?
or instagram had it blocked?

**Comment by Coto16** [comment]
Open instaBrute.py using Notepad++ or a similar text editor.

Go to line 132 and remove "profile", so it should be: driver = webdriver.Firefox()

Do the same with line 136.

Run the script normally.

**Comment by knat217** [comment]
try using firefox 45.0 with selenium-2.53.1

**Comment by ddev1234** [comment]
@Coto16 when u do that this happens..

C:\Users\User\Desktop\instabrute\instaBrute-master>instaBrute.py -f usernames.tx
t -d dictionary.txt
Using 1 seconds of delay
Traceback (most recent call last):
  File "C:\Users\User\Desktop\instabrute\instaBrute-master\instaBrute.py", line
141, in <module>
    main()
  File "C:\Users\User\Desktop\instabrute\instaBrute-master\instaBrute.py", line
132, in main
    driver.implicitly_wait(30)
TypeError: unbound method implicitly_wait() must be called with WebDriver instan
ce as first argument (got int instance instead)
