### ISSUE TITLE
almost

### ISSUE THREAD

**Issue by Deyelk** [chinoogawa/instaBrute#31]
Using 1 seconds of delay
Traceback (most recent call last):
  File "instaBrute.py", line 142, in <module>
    main()
  File "instaBrute.py", line 136, in main
    driver = webdriver.Firefox(profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x7fa3cbbd68d0>> ignored

**Comment by ecwebservices** [comment]
The same problem is trying to be figured out on #30

**Comment by antony-jr** [comment]
@Deyelk  @elijahcruz12 You could try my script which is much elegant and does not get stuck , it does not use a browser but instead mimics the instagram android apk , Try it at https://github.com/antony-jr/instagram-py ,This repo is the official one.
