### ISSUE TITLE
Blank Page FireFox

### ISSUE THREAD

**Issue by afuae** [chinoogawa/instaBrute#33]
**hi guys
i have problem with instaBrute that when i type 
instaBrute.py -f usernames.txt -d dictionary.txt**
**it shows me this after a while waiting in blank page firefox:**

Using 1 seconds of delay
Traceback (most recent call last):
  File "C:\Users\IDEAPAD 700\Desktop\New folder\instaBrute-master\instaBrute.py", line 142, in <module>
    main()
  File "C:\Users\IDEAPAD 700\Desktop\New folder\instaBrute-master\instaBrute.py", line 132, in main
    driver = webdriver.Firefox()
  File "C:\Python27\lib\site-packages\selenium-2.48.0-py2.7.egg\selenium\webdriver\firefox\webdriver.py", line 77, in __init__
    self.binary, timeout),
  File "C:\Python27\lib\site-packages\selenium-2.48.0-py2.7.egg\selenium\webdriver\firefox\extension_connection.py", line 49, in __init__
    self.binary.launch_browser(self.profile)
  File "C:\Python27\lib\site-packages\selenium-2.48.0-py2.7.egg\selenium\webdriver\firefox\firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable()
  File "C:\Python27\lib\site-packages\selenium-2.48.0-py2.7.egg\selenium\webdriver\firefox\firefox_binary.py", line 103, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.

**i searched a lot about this problem in many sites, I did not find a solution
please help :'(**

**Comment by jordan6522** [comment]
Have you found a solution? I am having the same issue. 
Thanks.
