### ISSUE TITLE
mechanize error

### ISSUE THREAD

**Issue by yagojohnny-design** [chinoogawa/instaBrute#57]
hello everyone,
i has this it erro, look

Traceback (most recent call last):
  File "instaBrute.py", line 2, in <module>
    from mainLib import *
  File "/home/hackingtool/instaBrute/instaBrute/mainLib.py", line 1, in <module>
    import mechanize
ImportError: No module named mechanize

who can help me?

**Comment by jimmyxan** [comment]
i got the same error... how can we solve?

**Comment by mahfelwp** [comment]
i got same error
